### ISSUE TITLE
500 error when posting

### ISSUE THREAD

**Issue by BandonRandon** [Automattic/cloudup-cli#51]
When I'm using `up FILE LOCATION` I am seeing a 500 bad gateway error:
``````
up /home/Desktop/Screenshot_14-04-2016-15:53:43.png
    Screenshot_14-04-201… : 0%
  Error: 502: <html>
  <head><title>502 Bad Gateway</title></head>
  <body bgcolor="white">
  <center><h1>502 Bad Gateway</h1></center>
  <hr><center>nginx/1.5.13</center>
  </body>
  </html>
   (POST /1/streams)
      at module.exports (/usr/local/lib/node_modules/up/node_modules/cloudup-client/lib/error.js:13:10)
      at /usr/local/lib/node_modules/up/node_modules/cloudup-client/lib/stream.js:335:32
      at Request.callback (/usr/local/lib/node_modules/up/node_modules/superagent/lib/node/index.js:628:30)
      at Request.<anonymous> (/usr/local/lib/node_modules/up/node_modules/superagent/lib/node/index.js:131:10)
      at emitOne (events.js:90:13)
      at Request.emit (events.js:182:7)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/up/node_modules/superagent/lib/node/index.js:773:12)
      at emitNone (events.js:85:20)
      at IncomingMessage.emit (events.js:179:7)
      at endReadableNT (_stream_readable.js:906:12)
```

**Comment by gowthamgts** [comment]
Me too got the problem.

**Comment by BandonRandon** [comment]
This issue has been resolved. Closing.

**Comment by gowthamgts** [comment]
Any idea why or how?

**Comment by TooTallNate** [comment]
The API server was down. Back up now.

**Comment by gowthamgts** [comment]
It was down for 2 days I guess. Thanks anyway.
